"""Live Isaac-loop attachment. Constructor/read tick are called on the sim thread.

Use with #44's verified isolated loop, after initialization; no Unitree DDS.
Candidate A uses ROS DDS only inside the verified loopback namespace.
No synthetic movement or control commands are generated by this tap.
"""
import csv
import time
from publishers import CustomPublisher, RosPublisher


class LiveBridgeTap:
    def __init__(self, robot, candidate, rate, output, socket_path=None, canonical_names=None):
        if rate not in (30, 60):
            raise ValueError("Compare 30 and 60 Hz")
        actual = list(robot.joint_names)
        names = list(canonical_names or actual)
        if len(set(names)) != len(names) or set(names) != set(actual):
            raise ValueError("Canonical names must exactly match the live articulation inventory")
        self.indices = [actual.index(name) for name in names]
        self.publisher = CustomPublisher(socket_path, names) if candidate == "custom" else RosPublisher(names) if candidate == "rosbridge" else None
        if self.publisher is None:
            raise ValueError("Unknown candidate")
        self.rate, self.next_tick = rate, time.monotonic()
        self.stream = open(output, "w", newline="", encoding="utf-8")
        self.writer = csv.writer(self.stream)
        self.writer.writerow(["seq", "host_monotonic_ns", "sim_step", "sim_time", "publish_call_ms", "process_cpu_s", "server_queue_overwrites"])

    def after_step(self, robot, sim_time, sim_step, object_poses=None):
        now = time.monotonic()
        if now < self.next_tick:
            return
        before = time.monotonic_ns()
        values = robot.data.joint_pos[0].tolist()
        frame = self.publisher.publish(sim_time, sim_step, [values[i] for i in self.indices], object_poses or [])
        cost = (time.monotonic_ns() - before) / 1e6
        self.writer.writerow([frame["seq"], frame["host_monotonic_ns"], sim_step, sim_time, cost,
                              time.process_time(), getattr(self.publisher, "overwrites", "")])
        self.stream.flush()
        self.next_tick += 1 / self.rate
        if self.next_tick <= now:
            self.next_tick = now + 1 / self.rate  # missed sim ticks are measured, never filled with fake frames

    def close(self):
        self.publisher.close()
        self.stream.close()
