using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo("AcousticVocab.SessionEngine.Tests")]
[assembly: InternalsVisibleTo("AcousticVocab.SessionEngine.PlayModeTests")]
[assembly: InternalsVisibleTo("AcousticVocab.Assessment.Tests")]
[assembly: InternalsVisibleTo("AcousticVocab.Assessment.PlayModeTests")]
[assembly: InternalsVisibleTo("AcousticVocab.Teaching.Tests")]
[assembly: InternalsVisibleTo("AcousticVocab.Teaching.PlayModeTests")]
[assembly: InternalsVisibleTo("AcousticVocab.SelectionMenus.Tests")]
[assembly: InternalsVisibleTo("AcousticVocab.DataLogging.Tests")]
